language: node_js
node_js:
  - "0.12"
before_install:
  - "export CHROME_BIN=chromium-browser"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - "npm install -g gulp jspm karma-cli"
  - "npm install"
  - "jspm config registries.github.auth $JSPM_GH_TOKEN"
  - "jspm install -y"
script:
  - "gulp test"
